name: "Tests for StudentSync API"

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev
        gem install bundler
        bundle install
        curl -L https://fly.io/install.sh | sh
        echo "$HOME/.fly/bin" >> $GITHUB_PATH

    - name: Set up database
      run: |
        bin/rails db:create
        bin/rails db:migrate

    - name: Run tests
      run: bundle exec rspec

    - name: Authenticate with Fly.io
      run: flyctl auth token --token ${{ secrets.FLY_API_TOKEN }}
    
    - name: Deploy to Fly.io
      if: success()
      run: flyctl deploy
